#!/bin/bash

module load cuda
module load cudnn
module load anaconda/5.1.0-py36

source activate GANS_7

host=`hostname -s`

echo $CUDA_VISIBLE_DEVICES

# Run on the first available GPU
# Note that this is an example. You can replace the channel and cut with other values (you will get an error if the cut has not been produced though)
# and you can add a version as well.
python three_layer_classifier.py --channel="ee" --cut=0.8 0
